export type ConstraintSource = "request" | "current_turn" | "recent_context" | "llm" | "memory" | "derived" | "default";
export type ConstraintPriority = "hard" | "soft";

export type AgentIntent =
  | "route_create"
  | "route_modify"
  | "route_compare"
  | "route_review"
  | "poi_discovery"
  | "navigation_query"
  | "info_query"
  | "memory_query"
  | "history_query"
  | "preference_feedback"
  | "social_copy"
  | "general_chat";

export type AgentResponseKind = "route" | "comparison" | "information" | "memory" | "social_copy" | "chat";

export interface IntentClassification {
  intent: AgentIntent;
  confidence: number;
  reason: string;
}

export interface ContentSection {
  title: string;
  items: string[];
}

export type InformationSourceType = "official_api" | "official_link" | "unverified";

export interface InformationSource {
  title: string;
  url: string;
  domain: string;
  snippet?: string;
  sourceType: InformationSourceType;
  verificationReason: string;
  provider: "tavily" | "amap" | "venue_provider";
  retrievedAt: string;
  publishedAt?: string;
}

export interface ComparisonOption {
  name: string;
  metrics: Record<string, string>;
  pros: string[];
  cons: string[];
}

export interface RouteComparison {
  dimensions: string[];
  options: ComparisonOption[];
  recommendation: string;
  missingInformation?: string[];
}

export interface SocialCopyVariant {
  tone: string;
  text: string;
  hashtags: string[];
}

export interface SocialCopyResult {
  variants: SocialCopyVariant[];
  basedOnRoute: boolean;
}

export interface IntentResponsePayload {
  title: string;
  answer: string;
  sections: ContentSection[];
  comparison?: RouteComparison;
  socialCopy?: SocialCopyResult;
  /** Server-owned citations collected from tools. The LLM is not allowed to fabricate these. */
  sources?: InformationSource[];
}

export interface RouteWeatherSummary {
  summary: string;
  risk: "low" | "medium" | "high";
  rainProbability: number;
  airQuality?: { aqi: number; category: string };
  warning?: string;
  advice: string[];
}

export interface RouteOverview {
  title: string;
  city: string;
  startPoint: string;
  endPoint?: string;
  stopCount: number;
  partyLabel: string;
  time: {
    totalMinutes: number;
    travelMinutes: number;
    stayMinutes: number;
  };
  cost: {
    total: number;
    perPerson?: number;
    budget?: number;
  };
  weather: RouteWeatherSummary;
  importantNotes: string[];
  tradeoffs?: ConstraintTradeoff[];
}

/**
 * A transparent disclosure of a constraint conflict, compromise, or data
 * limitation.  The planner keeps hard constraints authoritative, but exposes
 * the resulting trade-off so the user can choose a different optimization
 * direction on the next turn.
 */
export interface ConstraintTradeoff {
  id: string;
  kind: "conflict" | "uncertainty";
  severity: "info" | "warning" | "critical";
  affectedConstraints: string[];
  issue: string;
  decision: string;
  alternatives: string[];
  userChoiceRequired: boolean;
}

export interface ConstraintLedgerEntry {
  path: string;
  value: unknown;
  source: ConstraintSource;
  priority: ConstraintPriority;
}

export interface PartyConstraints {
  total: number;
  adults?: number;
  children?: number;
  childAges?: number[];
  seniors?: number;
  stroller?: boolean;
  mobilityNeeds: string[];
}

export interface RouteExperienceConstraints {
  familyFriendly?: boolean;
  pace?: "relaxed" | "normal" | "intensive";
  restStopRequired?: boolean;
  restroomPreferred?: boolean;
  avoidCrowds?: boolean;
}

/** Hard accessibility requirements that must not be treated as style hints. */
export interface AccessibilityConstraints {
  wheelchairAccessRequired?: boolean;
  stepFreeRequired?: boolean;
  elevatorRequired?: boolean;
  accessibleRestroomRequired?: boolean;
  frequentRestRequired?: boolean;
}

/**
 * An open-ended semantic description of the requested route style.
 * Theme names deliberately remain strings: examples such as "romantic" or
 * "literary" must not become the boundary of what the agent can understand.
 */
export interface StyleTag {
  name: string;
  weight: number;
  evidence?: string;
}

export interface DesiredScene {
  description: string;
  importance: number;
  searchHints?: string[];
}

export interface StyleIntent {
  /** Relevant wording preserved from the user instead of reducing it to a label. */
  rawText: string;
  /** A short semantic interpretation generated by the model or fallback compiler. */
  summary: string;
  tags: StyleTag[];
  desiredScenes: DesiredScene[];
  /** Negative aesthetics or scene qualities, e.g. "too commercial". */
  avoidances: string[];
  /** Searchable place qualities/categories, not fabricated POI names. */
  searchHints: string[];
  /** Desired progression between stops, expressed as open natural-language stages. */
  narrativeArc: string[];
  confidence: number;
}

/** Input form accepted from clients; nested fields are intentionally partial. */
export interface StyleIntentInput {
  rawText?: string;
  summary?: string;
  tags?: Array<{ name: string; weight?: number; evidence?: string }>;
  desiredScenes?: Array<{ description: string; importance?: number; searchHints?: string[] }>;
  avoidances?: string[];
  searchHints?: string[];
  narrativeArc?: string[];
  confidence?: number;
}

export interface UserConstraints {
  city: string;
  startPoint: string;
  durationMinutes?: number;   // undefined = no time limit
  budget?: number;            // undefined = no budget limit
  preferences: string[];
  peopleCount?: number;
  party: PartyConstraints;
  experience: RouteExperienceConstraints;
  accessibility: AccessibilityConstraints;
  style: StyleIntent;
  constraintLedger: ConstraintLedgerEntry[];
  transportMode?: "walk" | "transit" | "mixed";
  weatherPreference?: "avoid_rain" | "indoor_first" | "outdoor_ok";
  weatherRisk?: "low" | "medium" | "high";
  endPoint?: string;          // user-specified final destination
  maxLegMinutes?: number;     // max time per leg (walk/transit)
  /** True when preferences came from the current turn, not defaults or memory. */
  preferencesExplicit?: boolean;
  /** True when the value came from the current turn or recent thread context. */
  transportModeExplicit?: boolean;
  weatherPreferenceExplicit?: boolean;
  maxLegMinutesExplicit?: boolean;
  partyExplicit?: boolean;
  experienceExplicit?: boolean;
  styleExplicit?: boolean;
}

export interface PlanRequest {
  task?: string;
  city?: string;
  startPoint?: string;
  durationMinutes?: number;
  budget?: number;
  preferences?: string[];
  peopleCount?: number;
  party?: Partial<PartyConstraints>;
  experience?: RouteExperienceConstraints;
  accessibility?: AccessibilityConstraints;
  /** Optional structured style profile for advanced clients. Natural-language task is also parsed. */
  style?: StyleIntentInput;
  /** Raw open-ended style wording from a simple form field. */
  styleDescription?: string;
  transportMode?: "walk" | "transit" | "mixed";
  weatherPreference?: "avoid_rain" | "indoor_first" | "outdoor_ok";
  weatherRisk?: "low" | "medium" | "high";
  endPoint?: string;
  maxLegMinutes?: number;
  /** Frontend model selector: 'flash' = deepseek-v4-flash, 'pro' = deepseek-v4-pro */
  preferredModel?: "flash" | "pro";
  /** Memory scope. Memory is disabled for legacy requests without a userId. */
  userId?: string;
  /** Conversation scope used for recent-turn memory. */
  threadId?: string;
}

export interface RouteStop {
  name: string;
  category: PoiCategory;
  estimatedCost: number;
  estimatedStayMinutes: number;
  reason: string;
  location?: string;
  address?: string;
  /** City reported by the POI provider, used to reject cross-city results. */
  city?: string;
  rating?: number;
  distanceMeters?: number;
  /** Group total at this stop. */
  estimatedCostPerPerson?: number;
  /** Constraint matches used to explain why this POI was selected. */
  suitabilityTags?: string[];
  /** Semantic reasons this stop contributes to the requested style. */
  styleMatches?: string[];
  /** Combined lexical/vector/LLM style relevance, normalized to 0..1. */
  styleScore?: number;
  styleConflicts?: string[];
  /** LLM 生成的费用明细，说明每一项开销来源 */
  costBreakdown?: string;
  /** LLM 生成的亮点描述，一句话说明该地点特色 */
  highlight?: string;
  /** LLM 生成的预约提醒，如"需提前3天在公众号预约"、"免预约直接进入" */
  bookingInfo?: string;
}

export interface RouteLeg {
  origin: string;
  destination: string;
  originName?: string;
  destinationName?: string;
  distanceMeters: number;
  durationMinutes: number;
  mode: "walk" | "transit" | "bicycling";
  /** True when distance/time comes from a straight-line fallback rather than a routing API. */
  estimated?: boolean;
}

export type PoiCategory = "bookstore" | "cafe" | "sight" | "museum" | "mall" | "park" | "restaurant";

export interface AgentPlanStep {
  id: string;
  description: string;
  toolHint: "weather" | "poi_search" | "route_plan" | "constraint_check";
  dependsOn: string[];
  status: "pending" | "running" | "completed" | "failed";
}

export type StateEventType = "PLAN" | "THINK" | "ACTION" | "OBS" | "REFLECT" | "RESULT" | "ERROR";

export interface StateEvent {
  event_type: StateEventType;
  step_id?: string;
  total_steps?: number;
  content: string;
  tool_call?: {
    tool: string;
    input?: Record<string, unknown>;
    output?: unknown;
  };
  timestamp: string;
  context_snapshot?: Record<string, unknown>;
}

export type TraceStepType = "thought" | "tool_call" | "tool_result" | "final_answer";

export interface TraceStep {
  type: TraceStepType;
  content?: string;
  tool?: string;
  input?: Record<string, unknown>;
  output?: unknown;
}

export interface AgentTrace {
  task: string;
  steps: TraceStep[];
  metadata: {
    model?: string;
    agent_version?: string;
    total_tokens?: number;
    response_time_ms?: number;
    agent_id?: string;
    [key: string]: unknown;
  };
}

export interface PlanningResult {
  /** Server-owned history identity, used by direct favorite operations. */
  historyId?: string;
  intent: IntentClassification;
  responseKind: AgentResponseKind;
  title: string;
  summary: string;
  /** Direct answer for non-route intents. Route facts live in routeOverview/stops/routeLegs. */
  answer?: string;
  sections?: ContentSection[];
  comparison?: RouteComparison;
  socialCopy?: SocialCopyResult;
  sources?: InformationSource[];
  routeOverview?: RouteOverview;
  totalEstimatedCost: number;
  totalEstimatedMinutes: number;
  stops: RouteStop[];
  constraints: UserConstraints;
  routeLegs?: RouteLeg[];
  startLocation?: string;
  decisionLog: string[];
  planSteps?: AgentPlanStep[];
  events?: StateEvent[];
  trace?: AgentTrace;
  weatherRisk?: "low" | "medium" | "high";
  corrections?: string[];
  /** Explicit conflicts/compromises and the decision made by the planner. */
  tradeoffs?: ConstraintTradeoff[];
  memory?: {
    recalled: Array<{
      id: string;
      kind: "semantic" | "episodic" | "procedural";
      text: string;
      score: number;
      retrieval?: "lexical" | "vector" | "hybrid";
      lexicalScore?: number;
      vectorScore?: number;
    }>;
    learned?: Array<{
      event: "ADD" | "UPDATE" | "DELETE" | "NONE";
      key?: string;
      text?: string;
      reason: string;
    }>;
  };
}
